import { chromium } from "playwright";
import { config as loadEnv } from "dotenv";
import { readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
loadEnv();
const __dirname=dirname(fileURLToPath(import.meta.url));
const BASE=(process.env.LINKIT_BASE_URL||"https://report.linkit360.com").replace(/\/+$/,"");
const SESSION=process.env.LINKIT_SESSION_PATH||".session/storage-state.json";
const pdf=join(__dirname,"..","discovery","payway-gameshop-env.pdf");
const ctx=await (await chromium.launch({headless:true,args:["--no-sandbox"]})).newContext({storageState:JSON.parse(await readFile(SESSION,"utf8"))});
const page=await ctx.newPage();
const reqResp=[];
page.on("response",r=>{ if(/ticketing-infra\/request/.test(r.url())) reqResp.push(r.status()+" "+r.url()); });
await page.goto(BASE+"/ticketing-infra/create",{waitUntil:"networkidle"});
const jq=(name,vals)=>page.evaluate(({name,vals})=>{window.jQuery(document.querySelector(`select[name="${name}"]`)).val(vals).trigger("change");},{name,vals});
await jq("category",["3"]); await page.waitForTimeout(1500);
await jq("company",["6"]); await page.waitForTimeout(1000);
await page.evaluate(()=>{const r=[...document.querySelectorAll('input[name=service_type]')].find(x=>x.value==="project");r.click();});
await jq("country",["1"]); await page.waitForTimeout(1800);
await page.fill('input[name="project"]',"Gameshop");
await jq("sent_to[]",["infra@linkit360.com"]);
await page.fill('input[name="subject"]',"LinkIT - Infra - Change env gameshop");
await jq("classification",["2"]);
await page.fill('textarea[name="request_detail"]',"PayWay env vars for gameshop.mobi.");
await page.locator('input[name="files[]"]').setInputFiles(pdf);
await page.waitForTimeout(1200);
const ret=await page.evaluate(()=>{ try{ return infraRequestSubmit(); }catch(e){ return "threw: "+e.message; } });
await page.waitForTimeout(1500);
const swal=await page.evaluate(()=>({ popup: document.querySelector('.swal2-popup')?.innerText||null, confirmBtn: document.querySelector('.swal2-confirm')?.innerText||null }));
console.log("infraRequestSubmit() returned:", ret);
console.log("Swal:", JSON.stringify(swal));
// if confirm present, click it and watch network
if(swal.confirmBtn){ await page.click('.swal2-confirm'); await page.waitForTimeout(6000); }
console.log("network to /request:", reqResp);
console.log("final url:", page.url());
process.exit(0);
